defaults:
  - _self_
  - syms: c2c2c2
  - stl_data: cube
  - model_data: invariant

# dataset: ${model_data.dataset}
# model: ${model_data.model}

batch_size: 32
n_epochs: 20
lr: 0.00001
verbose: true

weights:
  save_weights: true
  save_epoch_modulus: 10