defaults:
  - _self_
  - syms: c2c2c2
  - stl_data: cube

dataset:
  _target_: datasets.DragDataset
  file_name: ${stl_data.file_name}
  norm_features: ${stl_data.norm_features}

model:
  _target_: models.InvariantDragMLP
  gspaceinfo: ${syms.act}
  hidden_dim: ${syms.hidden_dim}


batch_size: 32
n_epochs: 20
lr: 0.00001
verbose: true

weights:
  save_weights: true
  save_epoch_modulus: 10