dataset:
  _target_: datasets.DragMeshDataset
  attr_file: ${stl_data.file_name}
  mesh_file: ${stl_data.mesh_file}
  norm_features: ${stl_data.norm_features}

model:
  _target_: e3nn_examples.SimpleNetwork
  irreps_in: 5x0e
  irreps_out: 1x0e
  max_radius: 2.0
  num_neighbors: 5.0
  num_nodes: 5.0

# loader:
#   _target_: functools.partial
#   _args_: pytorch_geometric.data.DataLoader
