dataset:
  _target_: datasets.DragMeshDataset
  attr_file: ${stl_data.file_name}
  mesh_file: ${stl_data.mesh_file}
  norm_features: ${stl_data.norm_features}

model:
  _target_: models.DragMeshNetwork
  irreps_node_output: 1x0e

# loader:
#   _target_: functools.partial
#   _args_: pytorch_geometric.data.DataLoader
