dataset:
  _target_: datasets.DragMeshDataset
  attr_file: ${stl_data.file_name}
  mesh_file: ${stl_data.mesh_file}
  norm_features: ${stl_data.norm_features}
  data_lim: -1
  orientation_features: True

model:
  _target_: gcn.GCN
  in_channels: 7
  hidden_channels_list: [256, 256, 256, 256]
  out_channels: 1
  use_gdc: False