dataset:
  _target_: datasets.DragMeshDataset
  attr_file: ${stl_data.file_name}
  mesh_file: ${stl_data.mesh_file}
  norm_features: ${stl_data.norm_features}
  data_lim: -1
  return_features_separately: True

model:
  _target_: gnn_mlp_hybrid.GNN_MLP_Hybrid
  num_node_features: 5
  num_inp_feats: 5
  z_lmax: 4
  mlp_hidden: 128
  max_radius: 4.0
  out_dim_gnn: 32
  out_dim_mlp: 1
