dataset:
  _target_: datasets.DragDataset
  file_name: ${stl_data.file_name}
  norm_features: ${stl_data.norm_features}

model:
  _target_: models.InvariantDragMLP
  gspaceinfo: ${syms.act}
  hidden_dim: ${syms.hidden_dim}

# loader:
#   _target_: functools.partial
#   _args_: torch.utils.data.DataLoader
