_target_: src.data_modules.preprocessed_data_module.PreprocessedDragDataModule
data_dir: "/projects/gllab/sortur.n/drag_dataset_84k.pt"
batch_size: 2
num_workers: 4
validation_meshes: [0, 1, 2, 3, 4]
norm_features: true
