# configs/config.yaml

defaults:
  - trainer: default
  - model: ???
  - dataset: ???
  - syms: c2c2c2 
  # - logger: wandb     # Optional, defaulting to WandB
  - callbacks: model_checkpoint
  - _self_           # Allows values in this file to be used

# Global parameters
seed: 42
test_after_fit: false