# configs/config.yaml

defaults:
  - trainer: default
  - model: ???
  - dataset: ???
  - syms: c2c2c2 
  - callbacks: model_checkpoint_best
  - _self_           # Allows values in this file to be used

# Global parameters
seed: 42
test_after_fit: true
accumulate_grad_batches: 4
